module CalculatorApp {
    exception DivideByZero {
        string message;
    };

    interface Calculator {
        long add(in long num1, in long num2);
        long subtract(in long num1, in long num2);
        long multiply(in long num1, in long num2);
        double divide(in long num1, in long num2) raises (DivideByZero);
    };
};
